name: Temporary delete ambience test branch

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tmp-delete-ambience-branch.yml'

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete ambience test branch
        run: git push origin --delete test-ambiances
