name: Temporary delete test background branch

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tmp-delete-test-background.yml'

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete test branch
        run: git push origin --delete test-background
